[Examples] Add Maxim Web
vuejs/awesome-vue pull request #3763
Opened 2021-08-21 10:06 UTC by ericliang

### `General`
> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list

#### `Open Source`

- [x] Link description does not contain a link to an author / third-party resource
- [x] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product

#### `Apps/Websites`

- [x] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [x] The website is using vuejs intensively. It should detect vue with [vue-devtools](https://github.com/vuejs/vue-devtools).
  > If you cannot detect vue with `vue-devtools` due to work at non public pages (e.g. for enterprise website), you can send Pull Request with screenshot that detected it.
- [x] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [x] A commercial product using Vue, provided that guests could reasonably check out how Vue was used (i.e. A headless CMS which uses Vue for the Admin/editor Area and offers a free tier).

2021-08-21 17:36 UTC, Scrum requested changes

2021-08-21 17:36 UTC, Scrum commented on README.md
> +- [美信拓扑IM Web版](https://github.com/maxim-top/maxim-web) - A chat demo using [MaximTop](https://www.maximtop.com)'s IM SDK (floo).
Please use only titles in English only.

2021-08-22 03:17 UTC, ericliang commented on README.md
> +- [美信拓扑IM Web版](https://github.com/maxim-top/maxim-web) - A chat demo using [MaximTop](https://www.maximtop.com)'s IM SDK (floo).
Thanks for the review,  title changed.

2021-08-22 07:22 UTC, Scrum approved these changes

2021-08-22 07:22 UTC, merged

2021-08-22 09:24 UTC, ericliang commented
Thanks all 😊