added a gantt table component named jz-gantt
vuejs/awesome-vue pull request #3811
Opened 2021-11-04 02:13 UTC by jeremyjone

### `General`
> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list

#### `Open Source`

- [x] Link description does not contain a link to an author / third-party resource
- [x] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product

#### `Apps/Websites`

- [ ] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [ ] The website is using vuejs intensively. It should detect vue with [vue-devtools](https://github.com/vuejs/vue-devtools).
  > If you cannot detect vue with `vue-devtools` due to work at non public pages (e.g. for enterprise website), you can send Pull Request with screenshot that detected it.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [ ] A commercial product using Vue, provided that guests could reasonably check out how Vue was used (i.e. A headless CMS which uses Vue for the Admin/editor Area and offers a free tier).

2021-11-08 06:34 UTC, Scrum requested changes
## Checklist

- [ ] git: pull request template structure not broken
- [ ] git: pull request template not selected `type`
- [ ] git: pull request template not checked `Checklist`
- [ ] git: empty commit
- [ ] git: link not to repository
- [ ] git: link description contains a link to the author / third-party resource
- [ ] git: link description no `for Vite` or `Vite plugin`
- [x] git: link description short description short description (one sentence in 24 words, no expanded explanation)
- [x] git: terms in the wrong formats (e.g. Typescript over TypeScript)
- [ ] git: broken PR
- [ ] git: no conflicts resolved
- [ ] git: doublicate
- [ ] time: not updated for more than 6 months
- [ ] category: not in its category
- [ ] lists: not the last on the list
- [ ] docs: no documentation
- [ ] docs: non-english documentation
- [ ] project: commercial product
- [ ] project: dead project
- [ ] project: does not accept donat
- [ ] site: no link to the site
- [ ] site: site with errors
- [ ] site: not actively using vuejs
- [ ] site: not original
> Follow the rules [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md)

2021-11-08 06:59 UTC, jeremyjone commented
It has been modified as required

2021-11-08 10:44 UTC, Scrum requested changes

2021-11-08 10:44 UTC, Scrum commented on README.md
> + - [jz-gantt](https://github.com/jeremyjone/jz-gantt) - A high-performance vue gantt component, which includes highly customizable table columns, dynamic update data, freely drag the progress bar, sw
`vue` to Vue

2021-11-08 13:17 UTC, jeremyjone commented on README.md
> + - [jz-gantt](https://github.com/jeremyjone/jz-gantt) - A high-performance vue gantt component, which includes highly customizable table columns, dynamic update data, freely drag the progress bar, sw
It has been modified as required. `vue` to `Vue`

2021-11-08 13:17 UTC, jeremyjone commented
It has been modified as required. `vue` to `Vue`

2021-11-09 06:12 UTC, Scrum approved these changes

2021-11-09 06:12 UTC, Scrum commented
@jeremyjone need resolve conflicts

2021-11-09 07:35 UTC, jeremyjone commented
@Scrum  Conflict resolved. :)

2021-11-09 08:01 UTC, Scrum requested changes
incorrect resolved

2021-11-09 08:01 UTC, Scrum commented on README.md
> +<<<<<<< HEAD
?

2021-11-09 08:01 UTC, Scrum commented on README.md
> +=======
?

2021-11-09 08:01 UTC, Scrum commented on README.md
> +>>>>>>> a8e9ebad2b9da31b6d8aebee4fa0ad6809c7b719
?

2021-11-09 08:16 UTC, jeremyjone commented
Sorry, I didn't notice it. I have revised

2021-11-09 12:23 UTC, Scrum commented
> Sorry, I didn't notice it. I have revised

Please, create a new PR

2021-11-09 12:23 UTC, closed without merging