Fixed Typos and Grammatical Errors
vuejs/awesome-vue pull request #3851
Opened 2022-01-11 20:00 UTC by Cyebukayire

### `General`
> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [ ] Feature 
- [ ] Chore
### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [ ] Title as described
- [ ] Make sure you put things in the right category!
- [ ] Always add your items to the end of a list

#### `Open Source`

- [ ] Link description does not contain a link to an author / third-party resource
- [ ] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [ ] The documentation is in English.
- [ ] The project is active and maintained.
- [ ] The project accepts contributions.
- [ ] Not a commercial product

#### `Apps/Websites`

- [ ] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [ ] The website is using vuejs intensively. It should detect vue with [vue-devtools](https://github.com/vuejs/vue-devtools).
  > If you cannot detect vue with `vue-devtools` due to work at non public pages (e.g. for enterprise website), you can send Pull Request with screenshot that detected it.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [ ] A commercial product using Vue, provided that guests could reasonably check out how Vue was used (i.e. A headless CMS which uses Vue for the Admin/editor Area and offers a free tier).

2022-01-12 07:36 UTC, Scrum requested changes

2022-01-12 07:36 UTC, Scrum commented on README.md
> +- [AT-UI](https://at.aotu.io) - A fresh and flat UI-Kit especially for desktop application, made with ♥ by Vue.js 2.0
**e**specially ?

2022-01-12 08:01 UTC, Cyebukayire commented on README.md
> +- [AT-UI](https://at.aotu.io) - A fresh and flat UI-Kit especially for desktop application, made with ♥ by Vue.js 2.0
ohhhh Thank you, @Scrum
Grammarly was showing me an error but I've just found out that " Both can be used to mean "particularly." Especially tends to be more formal, while specially tends to be more informal " 
Let me change that back to "specially"

2022-01-12 10:51 UTC, Cyebukayire commented on README.md
> +- [AT-UI](https://at.aotu.io) - A fresh and flat UI-Kit especially for desktop application, made with ♥ by Vue.js 2.0
Done:)

2022-01-13 11:03 UTC, Scrum approved these changes

2022-01-13 11:04 UTC, merged